name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          git submodule update --init --recursive
          cd extern/box2d
          git checkout 9ebbbcd960ad424e03e5de6e66a40764c16f51bc
          mkdir build
          cd build
          cmake -DBOX2D_BUILD_DOCS=OFF -DBOX2D_BUILD_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="./" ..
          cmake --build . --config Release
          cmake --build . --target install --config Release
          cd ../../json
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="./" ..
          cmake --build .
          cmake --build . --target install
          cd ../../../src
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simulator
          path: src/build/Release/simulator.*

  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simulator

      - name: Create release
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
          gh release create ${VERSION} -t "${VERSION}" ./simulator.*

